### ISSUE TITLE
Some failure related to SWC minification

### ISSUE THREAD

**Issue by MarcoPolo** [ChainSafe/js-libp2p-noise#112]
First off, this is almost surely not a bug in js-libp2p-noise, but it is the thing that shows the error, so it's what I have to start with.

When using js-libp2p with [next.js](https://nextjs.org/) and swc minification enabled (soon to be the default), js-libp2p fails to connect to other peers. When dialing you get this error:

```
751-fd3143a979e6ab0f.js:formatted:19461 Uncaught AggregateError: 
    Error: Error occurred during XX handshake: Cannot decode stage 1 MessageBuffer: length less than 80 bytes.
        at x.performXXHandshake (http://localhost:8081/_next/static/chunks/751-fd3143a979e6ab0f.js:1:26499)
        at async x.performHandshake (http://localhost:8081/_next/static/chunks/751-fd3143a979e6ab0f.js:1:25429)
```

(The buffer is actually empty).

Here's a repro: https://github.com/MarcoPolo/libp2p-swc-next-bug

The real bug here is surely some swc transform that messes up this or some other js-libp2p code. But I'm not exactly sure how to figure out where exactly it's failing. I'm hoping you might have some more context in the best way to debug this.

Since this is really an ask for the best way to debug how a separate transform tool can mess up this codepath feel free to close as unactionable. I mostly have this here for posterity (maybe some other poor soul will find this issue).

**Comment by mpetrunic** [comment]
From quick looking, I would say it's something related to some libp2p transport library.
 Have you tried different encryption like libp2p-secio?
