### ISSUE TITLE
Error occurred during XX handshake

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/js-libp2p-noise#198]
```
2022-08-15T14:57:51.417Z libp2p:tcp:listener:error inbound connection failed Error: Error occurred during XX handshake: Value is null
    at Object.readLP (file:///home/cayman/Code/lodestar/node_modules/it-pb-stream/src/index.ts:63:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at XXHandshake.finish (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/handshake-xx.ts:124:46)
    at Noise.performXXHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:146:7)
    at Noise.performHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:125:12)
    at Noise.secureInbound (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:100:23)
    at EventTarget._encryptInbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:570:12)
    at EventTarget.upgradeInbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:175:13) {
  code: 'ERR_ENCRYPTION_FAILED'
}
```
```
2022-08-15T14:50:53.238Z libp2p:upgrader:error Failed to upgrade outbound connection UnexpectedPeerError: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.    at XXHandshake.exchange (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/handshake-xx.ts:103:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Noise.performXXHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:145:7)
    at Noise.performHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:125:12)
    at Noise.secureOutbound (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:68:23)
    at EventTarget._encryptOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:599:12)
    at EventTarget.upgradeOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:275:11)
    at TCP.dial (file:///home/cayman/Code/lodestar/node_modules/@libp2p/tcp/src/index.ts:37:18)
    at EventTarget.dial (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/transport-manager.ts:115:14) {
  code: 'ERR_ENCRYPTION_FAILED'
}
```
The first trace happens when we're the responder, after we've send our first noise handshake message, so my hunch is the peer didn't like something about the message and reset the connection
The second trace happens when we're the initiator, after we've received the first handshake message from the peer, its the first validation done on the message

**Comment by joeltg** [comment]
I'm also running into this while trying to set up a minimal libp2p node.

```ts
import { createLibp2p } from "libp2p"
import { TCP } from "@libp2p/tcp"
import { Noise } from "@chainsafe/libp2p-noise"
import { Mplex } from "@libp2p/mplex"
import { MulticastDNS } from "@libp2p/mdns"

const node = await createLibp2p({
	addresses: { listen: ["/ip4/127.0.0.1/tcp/8888"] },
	transports: [new TCP()],
	connectionEncryption: [new Noise()],
	streamMuxers: [new Mplex()],
	peerDiscovery: [new MulticastDNS()],
})

await node.start()
```

Running this on two machines on my network with `DEBUG=libp2p:* node test.js` shows the same errors. Any update or pointers here?

**Comment by joeltg** [comment]
Oh wait - this was all due to me binding to `/ip4/127.0.0.1/tcp/8888` instead of `/ip4/0.0.0.0/tcp/8888`... sorry for the ping :/

**Comment by joeltg** [comment]
Hmm I'm not sure what you mean - I think my problem was unrelated to the actual issue/topic here.

**Comment by mpetrunic** [comment]
This is now quite old, so I will assume it's no longer issue
